services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.14
    environment:
      SWAGGER_JSON: /swagger/swagger.yaml
    ports:
      - 2000:8080
    volumes:
      - ./swagger:/swagger

  analysis_service:
    build:
      context: ./analysis_service
      dockerfile: Dockerfile
    ports:
      - 5002:5000
    volumes:
      - ./data:/data
    container_name: analysis_service
  
  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    # ports:
    #   - 5001:5000
    volumes:
      - ./data:/data
    container_name: user_service

  payment_service:
    build:
      context: ./payment_service
      dockerfile: Dockerfile
    # ports:
    #   - 5003:5000
    volumes:
      - ./data:/data
    container_name: payment_service

  api_gatway:
    image: krakend
    container_name: api_gatway_ct
    volumes:
      - ./krakend:/etc/krakend/
    depends_on:
      - user_service
      - analysis_service
    ports:
      - 8080:8081
